/**
 * Wallet layer — connects @creit.tech/stellar-wallets-kit to the contract
 * client generated by `stellar contract bindings typescript`.
 *
 * In mock mode (NEXT_PUBLIC_MOCK=true), bet/claim/claimMany simulate a 1.5s
 * delay and return success so the full UI flow can be developed without a
 * testnet transaction.
 */

import { TESTNET } from "./bindings/addresses";
import { Client, networks, type Side } from "./bindings/index";

// ── Wallet kit (lazy — SSR safe) ──────────────────────────────────────────────

let kitInstance: import("@creit.tech/stellar-wallets-kit").StellarWalletsKit | null = null;

async function getKit() {
  if (kitInstance) return kitInstance;
  const { StellarWalletsKit, WalletNetwork, allowAllModules } = await import(
    "@creit.tech/stellar-wallets-kit"
  );
  kitInstance = new StellarWalletsKit({
    network: WalletNetwork.TESTNET,
    selectedWalletId: "freighter",
    modules: allowAllModules(),
  });
  return kitInstance;
}

// ── Contract client factory ───────────────────────────────────────────────────

function buildClient(publicKey: string) {
  return new Client({
    ...networks.testnet,
    rpcUrl: TESTNET.RPC_URL,
    publicKey,
  });
}

// ── Sign helper ───────────────────────────────────────────────────────────────

async function signTransaction(xdr: string): Promise<{ signedTxXdr: string; signerAddress?: string }> {
  const kit = await getKit();
  const { address } = await kit.getAddress();
  const { signedTxXdr } = await kit.signTransaction(xdr, {
    networkPassphrase: TESTNET.NETWORK_PASSPHRASE,
    address,
  });
  return { signedTxXdr, signerAddress: address };
}

// ── Wallet connect / disconnect ───────────────────────────────────────────────

export async function openConnectModal(onConnect: (address: string) => void): Promise<void> {
  const kit = await getKit();
  await kit.openModal({
    onWalletSelected: async (option) => {
      kit.setWallet(option.id);
      const { address } = await kit.getAddress();
      onConnect(address);
    },
  });
}

export async function disconnect(): Promise<void> {
  kitInstance = null;
}

export async function getAddress(): Promise<string | null> {
  try {
    const kit = await getKit();
    const { address } = await kit.getAddress();
    return address;
  } catch {
    return null;
  }
}

// ── Error parsing ─────────────────────────────────────────────────────────────

const CONTRACT_ERRORS: Record<number, string> = {
  3: "Invalid asset",
  4: "Round not found",
  5: "Betting is closed — this round is locked",
  6: "Round has not settled yet",
  7: "Round already settled",
  8: "Too early to settle",
  9: "Amount too small — minimum bet is 10 XLM",
  10: "You already have a position on this round",
  11: "Already claimed",
  12: "Nothing to claim",
  16: "A round already exists for this oracle tick",
  17: "Too many rounds in one batch — maximum 20",
};

export function parseContractError(err: unknown): string {
  const msg = String(err);
  // Look for contract error code pattern: Error(Contract, #N)
  const match = msg.match(/#(\d+)/);
  if (match?.[1]) {
    const code = parseInt(match[1]);
    return CONTRACT_ERRORS[code] ?? `Contract error #${code}`;
  }
  if (msg.includes("insufficient") || msg.includes("balance")) {
    return "Insufficient XLM balance";
  }
  if (msg.includes("UserDeclinedError") || msg.includes("declined")) {
    return "Transaction cancelled";
  }
  return "Transaction failed — check your wallet";
}

// ── Transactions ──────────────────────────────────────────────────────────────

const IS_MOCK = process.env.NEXT_PUBLIC_MOCK === "true";

function mockDelay(ms = 1500) {
  return new Promise<void>((r) => setTimeout(r, ms));
}

/**
 * Place a bet on a round.
 * Simulates in mock mode; submits a real Soroban transaction on testnet.
 */
export async function bet(
  roundId: string,
  side: "Up" | "Down",
  amountStroops: bigint
): Promise<void> {
  if (IS_MOCK) {
    await mockDelay();
    return;
  }

  const kit = await getKit();
  const { address } = await kit.getAddress();
  const client = buildClient(address);

  const contractSide: Side =
    side === "Up" ? { tag: "Up", values: undefined } : { tag: "Down", values: undefined };

  const tx = await client.bet({
    user: address,
    round_id: BigInt(roundId),
    side: contractSide,
    amount: amountStroops,
  });

  await tx.signAndSend({ signTransaction });
}

/**
 * Claim winnings for a single round.
 * Simulates in mock mode; submits a real Soroban transaction on testnet.
 */
export async function claim(roundId: string): Promise<void> {
  if (IS_MOCK) {
    await mockDelay();
    return;
  }

  const kit = await getKit();
  const { address } = await kit.getAddress();
  const client = buildClient(address);

  const tx = await client.claim({
    user: address,
    round_id: BigInt(roundId),
  });

  await tx.signAndSend({ signTransaction });
}

/**
 * Batch claim up to 20 rounds in one transaction.
 * Simulates in mock mode; submits a real Soroban transaction on testnet.
 */
export async function claimMany(roundIds: string[]): Promise<void> {
  if (IS_MOCK) {
    await mockDelay();
    return;
  }

  const kit = await getKit();
  const { address } = await kit.getAddress();
  const client = buildClient(address);

  const tx = await client.claim_many({
    user: address,
    round_ids: roundIds.map(BigInt),
  });

  await tx.signAndSend({ signTransaction });
}

export const CONTRACT_ID = TESTNET.FAIR_MARKET;
export const RPC_URL = TESTNET.RPC_URL;
export const NETWORK_PASSPHRASE = TESTNET.NETWORK_PASSPHRASE;
