/**
 * Wallet layer — connects @creit.tech/stellar-wallets-kit to the Soroban
 * contract generated by `stellar contract bindings typescript`.
 *
 * Every mutating call returns a TxResult so the UI can surface the
 * transaction hash and link to the Stellar explorer.
 *
 * In mock mode (NEXT_PUBLIC_MOCK=true), bet/claim/claimMany simulate the
 * wallet signing delay with a fake hash so the full state machine works.
 */

import { TESTNET } from "./bindings/addresses";
import { Client, networks, type Side } from "./bindings/index";

export interface TxResult {
  hash: string;
  /** Stellar expert explorer link for the transaction */
  explorerUrl: string;
}

const EXPLORER = "https://stellar.expert/explorer/testnet/tx";

// ── Wallet kit ────────────────────────────────────────────────────────────────

let kitInstance: import("@creit.tech/stellar-wallets-kit").StellarWalletsKit | null = null;

async function getKit() {
  if (kitInstance) return kitInstance;
  const { StellarWalletsKit, WalletNetwork, allowAllModules } = await import(
    "@creit.tech/stellar-wallets-kit"
  );
  kitInstance = new StellarWalletsKit({
    network: WalletNetwork.TESTNET,
    // No default wallet — the modal lets the user choose
    selectedWalletId: "freighter",
    modules: allowAllModules(),
  });
  return kitInstance;
}

// ── Contract client ───────────────────────────────────────────────────────────

function buildClient(publicKey: string) {
  return new Client({
    ...networks.testnet,
    rpcUrl: TESTNET.RPC_URL,
    publicKey,
  });
}

// ── Sign helper ───────────────────────────────────────────────────────────────

async function signTx(xdr: string): Promise<{ signedTxXdr: string; signerAddress?: string }> {
  const kit = await getKit();
  const { address } = await kit.getAddress();
  const { signedTxXdr } = await kit.signTransaction(xdr, {
    networkPassphrase: TESTNET.NETWORK_PASSPHRASE,
    address,
  });
  return { signedTxXdr, signerAddress: address };
}

// ── Wallet connect / disconnect ───────────────────────────────────────────────

export async function openConnectModal(onConnect: (address: string) => void): Promise<void> {
  const kit = await getKit();
  await kit.openModal({
    onWalletSelected: async (option) => {
      kit.setWallet(option.id);
      const { address } = await kit.getAddress();
      onConnect(address);
    },
  });
}

export async function disconnect(): Promise<void> {
  kitInstance = null;
}

export async function getAddress(): Promise<string | null> {
  try {
    const kit = await getKit();
    const { address } = await kit.getAddress();
    return address;
  } catch {
    return null;
  }
}

/** Fetch XLM balance from Horizon for a G-address. Returns null on error. */
export async function getXlmBalance(address: string): Promise<string | null> {
  try {
    const res = await fetch(
      `https://horizon-testnet.stellar.org/accounts/${address}`
    );
    if (!res.ok) return null;
    const data = (await res.json()) as {
      balances?: Array<{ asset_type: string; balance: string }>;
    };
    const native = data.balances?.find((b) => b.asset_type === "native");
    return native?.balance ?? null;
  } catch {
    return null;
  }
}

// ── Error parsing ─────────────────────────────────────────────────────────────

const CONTRACT_ERRORS: Record<number, string> = {
  3: "Invalid asset",
  4: "Round not found",
  5: "Betting is closed — this round is locked",
  6: "Round has not settled yet",
  7: "Round already settled",
  8: "Too early to settle",
  9: "Amount too small — minimum bet is 10 XLM",
  10: "You already have a position on this round",
  11: "Already claimed",
  12: "Nothing to claim",
  16: "A round already exists for this oracle tick",
  17: "Too many rounds in one batch (max 20)",
};

export function parseContractError(err: unknown): string {
  const msg = String(err);
  const match = msg.match(/#(\d+)/);
  if (match?.[1]) {
    const code = parseInt(match[1]);
    return CONTRACT_ERRORS[code] ?? `Contract error #${code}`;
  }
  if (msg.includes("insufficient") || msg.includes("balance")) {
    return "Insufficient XLM balance — get testnet XLM at friendbot.stellar.org";
  }
  if (msg.includes("UserDeclinedError") || msg.includes("declined")) {
    return "Transaction rejected in wallet";
  }
  if (msg.includes("NetworkError") || msg.includes("fetch")) {
    return "Network error — check your connection";
  }
  return "Transaction failed";
}

// ── Transactions ──────────────────────────────────────────────────────────────

const IS_MOCK = process.env.NEXT_PUBLIC_MOCK === "true";

function mockResult(): TxResult {
  const hash = Array.from({ length: 64 }, () =>
    Math.floor(Math.random() * 16).toString(16)
  ).join("");
  return { hash, explorerUrl: `${EXPLORER}/${hash}` };
}

async function mockDelay(ms = 1500): Promise<TxResult> {
  await new Promise<void>((r) => setTimeout(r, ms));
  return mockResult();
}

/**
 * Resolve the connected wallet address, or null if no wallet is active.
 * Used to decide whether to run a real transaction or the mock path.
 */
async function resolveAddress(): Promise<string | null> {
  try {
    const kit = await getKit();
    const { address } = await kit.getAddress();
    return address || null;
  } catch {
    return null;
  }
}

/**
 * Place a bet.
 * - Wallet connected → signs a real Soroban transaction (always, even in mock mode)
 * - No wallet → mock delay (UI development only)
 */
export async function bet(
  roundId: string,
  side: "Up" | "Down",
  amountStroops: bigint
): Promise<TxResult> {
  const address = await resolveAddress();
  if (!address) return mockDelay();

  const client = buildClient(address);
  const contractSide: Side =
    side === "Up" ? { tag: "Up", values: undefined } : { tag: "Down", values: undefined };

  const tx = await client.bet({
    user: address,
    round_id: BigInt(roundId),
    side: contractSide,
    amount: amountStroops,
  });

  const sent = await tx.signAndSend({ signTransaction: signTx });
  const hash = sent.sendTransactionResponse?.hash ?? "";
  return { hash, explorerUrl: `${EXPLORER}/${hash}` };
}

/**
 * Claim winnings for one round.
 * - Wallet connected → real transaction
 * - No wallet → mock delay
 */
export async function claim(roundId: string): Promise<TxResult> {
  const address = await resolveAddress();
  if (!address) return mockDelay();

  const client = buildClient(address);
  const tx = await client.claim({
    user: address,
    round_id: BigInt(roundId),
  });

  const sent = await tx.signAndSend({ signTransaction: signTx });
  const hash = sent.sendTransactionResponse?.hash ?? "";
  return { hash, explorerUrl: `${EXPLORER}/${hash}` };
}

/**
 * Batch claim up to 20 rounds in one transaction.
 * - Wallet connected → real transaction
 * - No wallet → mock delay
 */
export async function claimMany(roundIds: string[]): Promise<TxResult> {
  const address = await resolveAddress();
  if (!address) return mockDelay();

  const client = buildClient(address);
  const tx = await client.claim_many({
    user: address,
    round_ids: roundIds.map(BigInt),
  });

  const sent = await tx.signAndSend({ signTransaction: signTx });
  const hash = sent.sendTransactionResponse?.hash ?? "";
  return { hash, explorerUrl: `${EXPLORER}/${hash}` };
}

export const CONTRACT_ID = TESTNET.FAIR_MARKET;
export const RPC_URL = TESTNET.RPC_URL;
export const NETWORK_PASSPHRASE = TESTNET.NETWORK_PASSPHRASE;
